[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rustdoc.json"
